### ISSUE TITLE
No legend for colors in ch. 10

### ISSUE THREAD

**Issue by michielcock** [ubvu/vu101report#15]
In the introduction to ch. 10, you mention that in the graphs one bar is for the discipline at the VU, one for OECD and one for VU/VUmc in general. The following graphs use bars in different colors, but there is no legend to explain which bar is for which. Presumably they are in the same order as mentioned in the text of the introduction, but this could be made a little clearer.

**Comment by mosart** [comment]
Added a legend in commit f329a8750ec6ff1014aea11f45ef894d0a46425e
