### ISSUE TITLE
ch. 2: add number of respondents

### ISSUE THREAD

**Issue by michielcock** [ubvu/vu101report#18]
In ch. 2 we have the number of visitors of the website (839) and an estimated number of academic staff, but not the number of respondents. Even though that number is given later on, it would be very useful here as well, to make the success rate of the questionnaire (6000 people got the mail > 839 clicked on the url > 531 responded) more clear.

**Comment by mosart** [comment]
Dank je . gefixed in commit d373ece8d1e573c295b18eeab50945c4196ee971
